server:
  port: 8123
  servlet:
    context-path: /api

spring:
  application:
    name: sy-picture-backend

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3300/sy_picture
    username: root
    password: 123456
